### ISSUE TITLE
Add link from Bookmarks

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#101]
The main site and handbook are linked from the handbook here:

https://handbook.civicactions.com/en/latest/050-how-we-work/bookmarks/#useful-accessibility-extensions-to-install

I'd like folks at CA to be reminded about the accessibility site here and for them to bookmark it. 

This needs to wait on https://github.com/CivicActions/accessibility/issues/67

**Comment by lukefretwell** [comment]
Merged this with #35 

https://github.com/CivicActions/accessibility/issues/35
