### ISSUE TITLE
Highlight section on personalization

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#105]
I like what is being done here in AbilityNet. This was previously supported by the BBC:

https://mcmw.abilitynet.org.uk/

We should link to it if not include something like this somewhere in our site.

**Comment by lukefretwell** [comment]
Merged into https://github.com/CivicActions/accessibility/issues/115

**Comment by mgifford** [comment]
More details will be developed here https://docs.google.com/document/d/14XXdoxs4pqm1VJ4cLI1a1yabMhNJpzdUyl0zFZ2gqmA/edit?usp=sharing
