### ISSUE TITLE
Include videos to help learn how to use basic accessibility tools

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#108]
When available, link to the how to video to encourage folks to use different accessibility testing tools

WAVE
https://www.youtube.com/watch?v=ITUDiTgAZY0

Accessibility Insights
https://www.youtube.com/watch?v=BIu9ONdMGGg

Axe
https://www.youtube.com/watch?v=f_pW2EpwqG8

**Comment by lukefretwell** [comment]
Merged into https://github.com/CivicActions/accessibility/issues/114
