### ISSUE TITLE
Drupal issue 2766853 is not an accessibility bug

### ISSUE THREAD

**Issue by bbenjamin** [CivicActions/accessibility#11]
See comment #4 and #28 for more information.
The input they reference is already accessible. The person that filed the issue wanted to change how the input communicates itself to AT (a title attribute) to a label. They wanted to add a label element so they could use CSS with pseudo-selectors, there were no accessibility problems reported or discovered.

**Comment by mgifford** [comment]
I'm removing it here https://github.com/CivicActions/accessibility/pull/335/files

Thanks for the review & the recommendation.
