### ISSUE TITLE
Develop MVP accessibility guide

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#114]
[Working document](https://docs.google.com/document/d/1gc-76Hg4V5hQ7sb9VoTFPc-VSu5PPGt8Zlbfb4DmesY/edit?usp=sharing)

- [x] create doc
- [x] move website content to doc
- [x] set deadline (March 25)
- [x] publish MVP to site: https://accessibility.civicactions.com/guide
- [x] publish news post

**Comment by jerseycheese** [comment]
@lukefretwell #186 Has the content updates for the guide.

**Comment by jerseycheese** [comment]
#245 has the rest of the updates to the Tools section of the guide, just needs a review.
