### ISSUE TITLE
Better document operations

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#117]
- [ ] /ops page(?)
- [ ] add links or info to how we work (links to new issue templates)

**Comment by jaube05** [comment]
Created a Github repo in CA for documentation. This will be the main source for all documentation within the CA company and be used for Onboarding.
https://github.com/CivicActions/documenation

**Comment by jaube05** [comment]
After discussions with team about repo. Decided to just add a simple documentation file linked from the README file where new CA employees can read and understand how to contribute to the Accessibility CA Site.
