### ISSUE TITLE
Potential clarification for Drupal issue 3048785 in VPAT

### ISSUE THREAD

**Issue by bbenjamin** [CivicActions/accessibility#12]
Not sure if this detail is something that gets added to VPAT, but the phrasing "There are places where we are seeking to improve the focus for authors and administrators" does make it seem like it's an overall issue with Drupal, when it's something specific to an IE bug. The IE bug is:  element styled as  `display: flex` will receive focus on click. This is not specific to Drupal. 

The reason that issue 3048785 exists is because Claro's is committed to making **all** focus states visible. The IE11 bug focuses elements that really shouldn't be focusable, but Claro is going to make that focus state visible regardless.

**Comment by mgifford** [comment]
I've clarified this in this patch https://github.com/CivicActions/accessibility/pull/335/files

Thanks @bbenjamin for highlighting this! Sorry it took me so long to get to.
