### ISSUE TITLE
Jekyll accessibility testing with pa11y-ci + axe article

### ISSUE THREAD

**Issue by dmundra** [CivicActions/accessibility#125]
A suggestion that we write an article about our Jekyll accessibility testing with pa11y-ci + axe.

pa11y themselves use it https://github.com/pa11y/pa11y.github.io while other Jekyll sites like BBC's accessibility page do not https://github.com/bbc/accessibility-news-and-you and could easily do it in GitHub.

**Comment by lukefretwell** [comment]
@dmundra love it! Was talking to @mgifford about this last week. If you create a Google Doc, we can start working from that.

**Comment by dmundra** [comment]
Sounds good.

**Comment by dmundra** [comment]
Started the document: https://docs.google.com/document/d/1TZ4PZaKZ1udqhB1tA2J3yOJsqUL6-i6gWUOF962sYbg/edit?usp=sharing, not ready for review yet.

**Comment by mgifford** [comment]
Here's another Jekyll site to crawl:
https://github.com/GSA/accessibility-for-teams

**Comment by dmundra** [comment]
> https://github.com/GSA/accessibility-for-teams

@mgifford here you go https://github.com/dmundra/accessibility-for-teams/pull/1

**Comment by dmundra** [comment]
Another example https://github.com/dmundra/accessibility-1/pull/1/checks

**Comment by dmundra** [comment]
@lukefretwell I added the example link above and a short note to the document. Let me know what else I can provide. I got feedback from @billwanjohi that I incorporated as well (thank you, Bill)

**Comment by dmundra** [comment]
The article is up https://accessibility.civicactions.com/posts/automated-accessibility-testing-leveraging-github-actions-and-pa11y-ci-with-axe
