### ISSUE TITLE
Design a poster around visual impairments

### ISSUE THREAD

**Issue by mikang** [CivicActions/accessibility#134]
Research and design a poster around visual impairments which include the following:

- Examples of visual impairments (permanent, temporary, and situational)
- Technologies used
- What to keep in mind when designing for individuals with visual impairments
- Actionable suggestions

**Comment by lukefretwell** [comment]
@mikang note the posters here: https://github.com/UKHomeOffice/posters/tree/master/accessibility

As @mgifford they are open license so we can repurpose for the CivicActions Brand.

Might be good to make a checklist of the ones we like (posters and stickers) and redo them.

@mikang this process might help you learn holistically before doing just one poster.

**Comment by mikang** [comment]
Thanks, @lukefretwell - I will do a review of the research, along with posters and stickers, before starting to design a poster

**Comment by lukefretwell** [comment]
#249
