### ISSUE TITLE
Write-up yml + VPAT + CaC

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#2]
Let's discuss/document/socialize how .yml files can streamline the VPAT creation and also be incorporated into the Compliance as Code process.

## Post

Work in progress: https://docs.google.com/document/d/1XvSdZn6Q2mnvcVUnoB-Yxsn8IgzzPjLmoqlCkr5Sdgw/edit?usp=sharing

## Notes

"“Voluntary Product Accessibility Template” and “VPAT,” including the template format, are Federally Registered Service Marks of the Information Technology Industry Council (ITI). VPAT users agree not to deviate materially from the template format providedby ITI, and to use the service mark (“®”) where appropriate."

## References

* https://www.itic.org/policy/accessibility/vpat
* https://github.com/benbalter/jekyll-accessibility-template
* https://www.section508.gov/sell/vpat

cc @mgifford @grugnog

**Comment by lukefretwell** [comment]
@benbalter @grugnog @openprivacy do you know of any efforts to build yml templates/files for VPATs, and is this being incorporated into the compliance process?

**Comment by grugnog** [comment]
It might ultimately be ideal if a standard VPAT data format could be adopted upstream at ITI.
Looking at https://www.itic.org/about/membership/iti-members it appears like membership is pretty much "big tech" only, but RedHat is a member and may an interesting proxy to pursue this (if we can find the right person), given that they have people familiar with Compliance as Code.

**Comment by openprivacy** [comment]
I don't know of any such efforts in the compliance as code community, but I believe it is a worthwhile initiative. I know some CaC folk at Red Hat that may know some folk...

**Comment by mgifford** [comment]
EARL also seems like it would fit into a Complaince as Code approach:
https://www.w3.org/WAI/standards-guidelines/earl/

**Comment by lukefretwell** [comment]
I've created a post related to this. Would love any feedback folks have:

https://docs.google.com/document/d/1XvSdZn6Q2mnvcVUnoB-Yxsn8IgzzPjLmoqlCkr5Sdgw/edit?usp=sharing

**Comment by lukefretwell** [comment]
Article here: https://gcn.com/articles/2021/02/04/accessibility-compliance-as-code.aspx
