### ISSUE TITLE
Feature request: Add site search

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#204]
**Describe the solution you'd like**

Add site search

**Comment by dmundra** [comment]
@lukefretwell did some research into search options. Found a few from Jekyll and searching:

* https://github.com/algolia/jekyll-algolia
* https://github.com/christian-fei/Simple-Jekyll-Search

The first one needs an external service provided but the second one doesn't. I think the Simple one could work but could take a little bit to add to the current theme. USWDS Jekyll uses search service provided by https://search.usa.gov/search so we cannot use that.

**Comment by dmundra** [comment]
We could use Google Custom Search as another fallback option.

**Comment by lukefretwell** [comment]
@dmundra see what I did on DistributedGov, which I think is the simple Jekyll search:

* https://distributedgov.com/search
* https://github.com/distributedgov/distributedgov.github.io/blob/master/search.json

**Comment by dmundra** [comment]
Yup @lukefretwell that is what I found. Cool, I think I use that to implement a version for us.
