### ISSUE TITLE
Develop prototye of Federalist + automated testing tools to socialize to federal government community

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#209]
Per internal conversation, develop a sandbox of [Federalist](https://github.com/18F/federalist) and incorporate the automated testing tools we integrated into the CivicActions Accessibility website.

Also:

* Write up recommendations
* Submit pull request to the [Federalist repo](https://github.com/18F/federalist

**Comment by dmundra** [comment]
On Friday I tried to get the Federalist repo running locally and reviewing how they do local testing. I am new to React and their frontend testing so I couldn't immediately inject axe testing. I also couldn't get the local version running so I will revisit this one later.

**Comment by dmundra** [comment]
This was my mistake. I was targetting getting accessibility testing the main Federalist website and not their Jekyll version https://github.com/18F/federalist-uswds-jekyll which does have accessibility testing using [a11y](https://www.npmjs.com/package/a11y) and CircleCI.

**Comment by dmundra** [comment]
Here is the PR for the federalist uswds jekyll site: https://github.com/18F/federalist-uswds-jekyll/pull/172
