### ISSUE TITLE
Consider adding GitHub Discussions to get insights or thoughts from users.

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#218]
More info on Discussions here - https://docs.github.com/en/discussions

Maybe it is the QA feature or an open ended discussion topic.  

Could possibly be tied around the guide or playbook, or even specific sections of the site..

**Comment by dmundra** [comment]
Similar to #250, which one to keep?

**Comment by mgifford** [comment]
I'm going to defer to #250 as there's just more context for it.
