### ISSUE TITLE
Blog post on use of retext

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#268]
Similar to: https://accessibility.civicactions.com/posts/automated-accessibility-testing-leveraging-github-actions-and-pa11y-ci-with-axe

cc @dmundra @mgifford

**Comment by dmundra** [comment]
Collecting useful links:
* Retext features inspired by https://github.com/sparkartgroup/quality-docs/ and used in CA handbook https://github.com/CivicActions/handbook
  * Readibility: https://github.com/retextjs/retext-readability
  * Equality: https://github.com/retextjs/retext-equality
  * Simplify: https://github.com/retextjs/retext-simplify
  * Contractions: https://github.com/retextjs/retext-contractions
* Review dog: https://github.com/reviewdog/reviewdog
* Retext: https://github.com/retextjs/retext

**Comment by dmundra** [comment]
Example of output seen here https://github.com/CivicActions/accessibility/pull/266/files

**Comment by dmundra** [comment]
Started google doc: https://docs.google.com/document/d/1CnIHl3tt9bO3xT-9s3C95KYX6EkWhIMybCOrBchNL5w/edit# (internal CA)

**Comment by dmundra** [comment]
The document is ready for review, I need to add some more examples but I need pull requests with text changes to be added to the repo. I think text changes are coming to help generate examples.

**Comment by mikang** [comment]
@dmundra I reviewed the doc and added some comments. Looks great!

**Comment by dmundra** [comment]
Thanks for the feedback, @mikang. I made some changes and would love your review again.

**Comment by mikang** [comment]
Just added a comment about one comma, and otherwise, I have no further comments, @dmundra !

**Comment by lukefretwell** [comment]
@dmundra this is probably for a new issue, but would be great to incorporate in some of the recommendations from 18F's content guide: https://content-guide.18f.gov/our-style/

**Comment by lukefretwell** [comment]
@dmundra this is great. I made some edits and pinged @Marlena-Medford to see if she could review for copy edits.

**Comment by dmundra** [comment]
Thanks @lukefretwell.
