### ISSUE TITLE
Main menu change order

### ISSUE THREAD

**Issue by jaube05** [CivicActions/accessibility#292]
Would like to adjust the main menu to be:
About
  -People
  -Contact
  -What is Accessibility
  -Projects
Calendar
  -Join us
New
Playbook
Guide

**Comment by mgifford** [comment]
Currently it is:
* About
* Join us
* Calendar
* News
* People
* Playbook
* Guide
* Contact
* Search

Did you mean "New" or "News"? 

How would this new order affect users? How about for [Emery](https://accessibility.civicactions.com/personas/engineer-emery)?

**Comment by jaube05** [comment]
Yes It was meant to News. 
I find the main navigation has too many menu items, and some can be categorized.
For instance, Contact - should probably not be in the main menu, as its in the footer and could fall under the About menu.
