### ISSUE TITLE
Feature request: Add drop down functionality to main menu

### ISSUE THREAD

**Issue by jaube05** [CivicActions/accessibility#294]

**Comment by mgifford** [comment]
Looking to just extend the heading menu with something like https://designsystem.digital.gov/components/header/ ?

**Comment by jaube05** [comment]
To have the main menu like this https://www.pc.gc.ca/en/index

**Comment by mgifford** [comment]
Gotta find one using the USWDS theme.. I think it's doable though.

**Comment by jaube05** [comment]
Found this https://designsystem.digital.gov/components/header/#basic-header-with-megamenu, but now im noticing the header doesnt look our header, should this be updated? @mgifford

**Comment by mgifford** [comment]
Might be worth exploring..  Can you mock something up proposing what the new menu might look like? I'm having trouble seeing it in my mind.

**Comment by jaube05** [comment]
@mgifford Something like this header
![Screen Shot 2021-04-21 at 10 33 26 AM](https://user-images.githubusercontent.com/62511019/115571634-2df43680-a28d-11eb-8b32-3f73c1258f9e.png)
