### ISSUE TITLE
Feature request: Add plain language page to guide

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#313]
**Describe the solution you'd like**

Would be great to have information related to plain language in the guide, including:

* Overview
* Best practices (or links to)
* Links to government resources (community of practice, websites, videos)
* Related automated testing tools

(@niradatta1 this might be of interest to you)

**Comment by mgifford** [comment]
Some resources:

- https://www.plainlanguage.gov/
- https://www.youtube.com/watch?v=fYJUdp83f_M
- https://digital.gov/communities/plain-language/
- https://accessibility.digital.gov/content-design/plain-language/
- https://digital.gov/event/2021/03/10/plain-language-and-section-508/
- https://www.accessibility.sa.gov.au/your-role/content/plain-language
- http://simplyaccessible.com/article/whitney-quesenbery/
- https://knowbility.org/programs/accessu-2021/plain-language-increasing-the-accessibility-of-your-content

**Comment by niradatta1** [comment]
https://docs.google.com/document/d/1QwQw3NiusI3crGt88rIkRlG8uCgCfIoHeWIL6UTv6AE/edit# Link to working draft

**Comment by lukefretwell** [comment]
@niradatta1 I worked on the doc a bit. Feel free to override any of my changes. Let me know if you'd like to debrief or co-work on it.

**Comment by lukefretwell** [comment]
@niradatta1 this is looking great! Added feedback. Once you're ready, let me know if you'd like support on pushing it to the live site.

**Comment by mgifford** [comment]
Do we want this on aCA or on a Medium blog or posted elsewhere? It isn't very technical so may get shared more in other environments.

**Comment by niradatta1** [comment]
@mgifford Would love to post this on Medium!
I think for the CA blog, we could do the spin-off article explaining the outcomes of your automated plain language testing.

**Comment by niradatta1** [comment]
@lukefretwell  Addressed everyone's comments, and resolved them in the draft --- I ran it again through the Hemingway App and it's at a Grade level 5. I think we're ready to post! How can we push this to the live site? Thanks!
