### ISSUE TITLE
Clarify accessibility in "Welcome to Design at CA"

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#337]
Work to document the differences between how we approach accessibility in various stages of our design. [Development in GoogleDoc](https://docs.google.com/document/d/1KGi7nUhAK5wBNjogbtKxP-zbmsMj6c1zUr5lBM4jebs/edit).

**Comment by niradatta1** [comment]
Hi Mike, @mikang and I already have a ticket that relates to this work (I tagged you, Issue #50). Would be great if we can capture our thoughts in the doc we started: https://docs.google.com/document/d/1rFb1sYwSYBicRlz1CU_hEWQRV8v-t_UJ-rp1ZKfqPSI/edit

**Comment by mgifford** [comment]
Oops..  And thanks!
