### ISSUE TITLE
Set up CivicActions Accessibility Newsletter

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#34]
### Newsletters
- https://a11yweekly.com/
- https://davebanesaccess.org/my-newsletter
- https://www.microassist.com/digital-access/news/
- https://www.d.umn.edu/itss/training/online/webdesign/webdev_listserv.html
- https://www.digitala11y.com/digital-accessibility-newsletters-roundup/
- https://www.webaxe.org/digital-accessibility-newsletters/

### OpenConcept
- https://mailchi.mp/133e3c60c3f6/accessibility-action
- https://us1.campaign-archive.com/home/?u=1a53770f122a75549b5af6097&id=e836043476

**Comment by mgifford** [comment]
Build content strategy and promote newsletter. Possible white labeling.

**Comment by lukefretwell** [comment]
@mgifford seems like we should just document the best ones and reference them in the guide.

**Comment by mgifford** [comment]
Or we just point to these two lists of newsletters:
https://www.digitala11y.com/digital-accessibility-newsletters-roundup/
https://www.webaxe.org/digital-accessibility-newsletters/

And say something like, each newsletter has a different focus, but for people getting into digital accessibility, https://a11yweekly.com provides a nice introduction with a fresh introduction of content every week that is easy to absorb. 

Something like that in any case.

**Comment by lukefretwell** [comment]
@mgifford yes, I'm closing this, and we can add a list to the guide.
