### ISSUE TITLE
Create Accessibility Metrics Dashboard

### ISSUE THREAD

**Issue by niradatta1** [CivicActions/accessibility#340]
I want to understand how to measure success of the accessibility site against our top metrics (captured in following doc): 

https://docs.google.com/document/d/1nggQ1u_cm8eRM7DCKQH0Evwg2FvumRjOGMpn4MV6K5E/edit

Developing a dashboard will help our team capture data in real-time and monitor against our measures of success.

Comments from Luke: 
- create an issue template with a checklist (similar to what we did for retrospectives)
- would be fun to use https://datastudio.google.com/u/0/
datastudio.google.comdatastudio.google.com

**Comment by niradatta1** [comment]
@dmundra to research how to integrate our metrics into the Google Insights Dashboard; understand how GA defines user engagement. 

@jaube05 Is there a way to integrate Contact Us data into GA? Would be great if we can include it as part of a single dashboard.

**Comment by dmundra** [comment]
Looks like we are collecting data in google analytics for the custom insights and conversions. Responded to the google document.

**Comment by lukefretwell** [comment]
Published: https://accessibility.civicactions.com/analytics

**Comment by dmundra** [comment]
Hey @niradatta1, is there anything else on this we need to do? If not we think this can be closed.
