### ISSUE TITLE
Setup recognition of significant Accessibility Days

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#37]
Description:
* Nov 30th - https://en.wikipedia.org/wiki/Blue_Beanie_Day
* Dec 3rd - UN International Day of Persons with Disabilities - https://www.un.org/en/observances/day-of-persons-with-disabilities
* May 20th, 2021 - GAAD - https://globalaccessibilityawarenessday.org/

**Comment by mgifford** [comment]
https://disabilityin.org/resource/2021-calendar-of-disability-related-dates/
https://www.microassist.com/digital-accessibility/disability-awareness-calendar/

I posted some of this here https://github.com/CivicActions/accessibility/issues/33

**Comment by lukefretwell** [comment]
Folded into #33
