### ISSUE TITLE
Adjust styling of anchor links so they don't overflow on the sidebar navigation

### ISSUE THREAD

**Issue by jaube05** [CivicActions/accessibility#371]
<img width="660" alt="Screen Shot 2021-05-05 at 12 10 40 PM" src="https://user-images.githubusercontent.com/62511019/117173739-12178700-ad9b-11eb-9371-ffb93badde37.png">

**Comment by dmundra** [comment]
@jaube05 when you get a chance can you also look at Mike’s PR: #356. I think they are related and the fixes to both could go in that pull request or together at least.
