### ISSUE TITLE
Define approach to automated testing (pa11y vs circle-ci vs ...)

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#39]

**Comment by dmundra** [comment]
See #52 and #94 for an example of pa11y-ci with the accessibility site.

**Comment by dmundra** [comment]
Cypress testing with axe resource: https://timdeschryver.dev/blog/setting-up-cypress-with-axe-for-accessibility

**Comment by dmundra** [comment]
@lukefretwell and @mgifford, this page https://accessibility.civicactions.com/playbook/automated-testing covers quite a bit. If I do write up a CA project cypress+axe example where would that go? On that page or a different page?

**Comment by mgifford** [comment]
@dmundra I'd add it to that page for now. Might make sense to spin it off onto another page at some point but that is easy enough to do.
