### ISSUE TITLE
Develop CivicActions Accessibility offering (strategy + services)

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#41]
We need to be clear to our clients what we are offering.

- [x] Create recurring sales/marketing check-in
- [x] Create deck ([working deck](https://docs.google.com/presentation/d/1SHQ6_2BYRNsL4tQRoHexXM7d7KxCgMByZBlQ0Vv_Cmg/edit?usp=sharing))
- [x] Update web page: https://accessibility.civicactions.com/services

**Comment by mgifford** [comment]
There is an initial sketch of this here https://docs.google.com/document/d/1saQGBapX2p62ipPe63nlBEDKmMklDqD89w-cG9LR5bA/edit#

This is an internal sales document at this.

**Comment by lukefretwell** [comment]
@mgifford I'm stumbling across various documents that would be great to better document here.

* [Strategy](https://docs.google.com/document/d/1WRs6YQhErTRJQOm8j6PPN0gyykslDqpOMwpBC1ZptpM/edit?usp=sharing)
* [Offerings](https://docs.google.com/document/d/1saQGBapX2p62ipPe63nlBEDKmMklDqD89w-cG9LR5bA/edit?usp=sharing)

It's not clear to me that the second doc is an offering?

**Comment by mgifford** [comment]
Maybe..  Not sure we want to mess up the practice area and service area.  

They both need more clarity. Some parts of them might be better as an email or an attachment to a potential client.  

They need to be fleshed out and then discussed with the sales team.  When we're clear on the the sales approach then we'll need to find ways to point people to a call to action from the practice area.  

I can't focus on this now though.

**Comment by mgifford** [comment]
Internal document about site-wide - https://docs.google.com/document/d/1saQGBapX2p62ipPe63nlBEDKmMklDqD89w-cG9LR5bA/edit#heading=h.c23t5pc7r3b9

**Comment by mgifford** [comment]
This is being developed here https://accessibility.civicactions.com/services

**Comment by lukefretwell** [comment]
Deck: https://docs.google.com/presentation/d/1H6bhM6wqFIds3cXCI3eE0YD65_GmYKzwRviuhs4Jj7s/edit?usp=sharing
