### ISSUE TITLE
Include Onboarding document into aCA site

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#424]
Currently it is just a MD file
https://github.com/CivicActions/accessibility/blob/main/Onboarding.md

**Comment by mgifford** [comment]
This probably should go as a guide page. Either way it is worth doing a micro-blog about it to highlight our work on this area.

**Comment by mgifford** [comment]
Adding this here https://github.com/CivicActions/accessibility/pull/493

**Comment by lukefretwell** [comment]
@mgifford here's code for the redirect to be added to the front matter:

```
redirect_from:
- /contact 
```

**Comment by mgifford** [comment]
I could be wrong, but that's only going to work if we think folks are landing on:
- https://accessibility.civicactions.com/Onboarding
- https://accessibility.civicactions.com/Onboarding.html

I have been sending folks here:
- https://github.com/CivicActions/accessibility/blob/main/Onboarding.md

Which isn't running Jekyll, thus the need to put in a link.

I think if we resolve this point we can close this issue.
