### ISSUE TITLE
Reduce hover/focus on cards to limit flashes

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#429]
I got this feedback after showing the site to a friend:

"Can I suggest making the hover less contrast.. running your mouse over the personas flashes, can be distracting or more for some"

It is pretty dramatic as we have right now. I can definitely see advantages to toning it down a bit, or perhaps introducing a fade so that there is less flashing.

**Comment by shawnthompson** [comment]
Maybe even using reduced motion media query in the CSS. For those who actually know about it in the settings of their OS.

**Comment by dmundra** [comment]
@shawnthompson that is a good suggestion. I will incorporate that in the fix. We also mention that in the playbook: https://accessibility.civicactions.com/playbook/personalization#checklist
