### ISSUE TITLE
Bug report: Anchor link icon not visible on small screen

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#437]
**Describe the bug**
A clear and concise description of what the bug is, in a user story format.
While visiting the site as a CivicActioner, I expected to have visibility to the subheading anchor links but observed but I don't see it on small screens, as it's to the left of the heading and gets hidden.

**To Reproduce**
1. Go to https://accessibility.civicactions.com/personas/accessibility-avery#description
2. Make browser small (or view on phone)

**Expected behavior**
Expect to see the anchor link and/or click on it.

**Screenshots**

<img width="375" alt="Screen Shot 2021-05-25 at 10 18 47 AM" src="https://user-images.githubusercontent.com/1569463/119567788-95584700-bd61-11eb-8b01-3e80f4dd7e66.png">

**Suggestion**

Place the anchor link icon to the right of the heading.

**Comment by mgifford** [comment]
I like that suggestion for the mobile view. @jaube05 do you think you can roll up the CSS so that it appears on the right for mobile where the left margin is so tiny?

**Comment by lukefretwell** [comment]
@mgifford I'd keep it consistent for all sizes.

**Comment by dmundra** [comment]
I think we could follow GitHub's lead, no hover on mobile and still left-aligned. E.g. 
![Screenshot of the accessibility repo README on GitHub](https://user-images.githubusercontent.com/7096681/119575938-a195d180-bd6c-11eb-9417-175541aeed3d.png)

**Comment by mgifford** [comment]
Look @dmundra that is exactly what I was about to type. And you included a screenshot too!  :)
