### ISSUE TITLE
Feature request: Add role-based pages

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#479]
**For whom is this feature?**

As Accessibility Avery, Designer Darcy, Engineer Emery, Procurement Parker, QA Quincy, Remote Raz, and CivicActioner, I want to know what I don't know about accessibility, so that I apply this into my work.

**Describe the solution you'd like**

- [x] Create a 'roles' filter in each yml/md file.
- [x] Add a page for each role/persona that synthesizes tools, resources, etc. 

## Example

* /roles
* /designer

## Roles

- Executive
- Procurement
- Development
- Product management
- Project management
- Operations
- Design
- Content

**Comment by dmundra** [comment]
#483 and #484 adds this feature.
