### ISSUE TITLE
Collect resources distributed teams & accessibility

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#48]
We are a distributed team. We should have best practices that we are working on here.

### Resources
- https://www.ryerson.ca/accessibility/guides-resources/virtual-meetings/
- https://www.nad.org/videoconferencing-platforms-feature-matrix/
- https://medium.com/cmcnally/accessibility-strategies-for-deaf-hard-of-hearing-people-in-remote-meetings-e19781b3bc4
- https://disabilityin.org/resources2/covid-19-response-accessible-tools-and-content/
- https://www.toolbox.com/hr/hr-strategy/articles/has-remote-work-increased-disability-inclusion-in-workplace/
- https://angel.co/blog/how-remote-work-impacts-employees-with-disabilities
- https://www.forumone.com/ideas/an-accessibility-inclusion-checklist-for-virtual-events/
- https://equalentry.com/slack-vs-discord-which-is-better-for-screen-readers/
- https://www.access-board.gov/about/meetings.html

**Comment by mgifford** [comment]
This maybe should be a new card but https://studio20.bccampus.ca/presenter-toolkit/

**Comment by lukefretwell** [comment]
Merged with https://github.com/CivicActions/accessibility/issues/115
