### ISSUE TITLE
Create accessibility@civicactions.com email

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#5]
- [x]  set up in groups
- [x] review settings
- [x]  add team members
- [x] add to website

**Comment by mgifford** [comment]
Who should get it? I am happy to, but would love to have others too. How do we manage email in group aliases at CA?

**Comment by lukefretwell** [comment]
I set up the accessibility@civicactions email but can't figure out how to allow external emails. Any ideas @mgifford @grugnog?

**Comment by lukefretwell** [comment]
Thank you @grugnog!
