### ISSUE TITLE
Feature request: Design roles pages

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#505]
**For whom is this feature?**
A clear and concise user story.
As Accessibility Avery, Designer Darcy, Engineer Emery, Procurement Parker, QA Quincy, Remote Raz, and CivicActioner, I want to see a nicely design page for each role, so that I easily understand how I specifically can better, and easily, get my head around accessibility in the context of my work.

**Describe the solution you'd like**
Add design to the respective roles pages so that they're more welcoming, less intimidating.

**Additional context**

https://accessibility.civicactions.com/roles/

**Comment by dmundra** [comment]
Related merge request #483

**Comment by jaube05** [comment]
As discussed in 06/29 check in call will be taking this ticket.
