### ISSUE TITLE
Semantic HTML for readmode Learning

### ISSUE THREAD

**Issue by jaube05** [CivicActions/accessibility#538]
https://docs.google.com/document/d/1XtpF7XkaKJ-gHMp1QBIblZ2lTrmVsdYn9uum2C89DbM/edit#

**Comment by jaube05** [comment]
https://docs.google.com/document/d/1XtpF7XkaKJ-gHMp1QBIblZ2lTrmVsdYn9uum2C89DbM/edit#

**Comment by mgifford** [comment]
Rough notes from my earlier work here https://github.com/mgifford/reader-mode-testing
