### ISSUE TITLE
GitHub page build errors

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#54]
We're randomly getting page build errors. Anyone have ideas as to why?

**Comment by dmundra** [comment]
Where are you seeing the errors? I am new to github-pages feature so I likely looking in the wrong places.

**Comment by lukefretwell** [comment]
Getting this again. After a few rebuild attempts, it finally worked.

![FireShot Capture 593 - Update news _ profile pages · CivicActions_accessibility@e7b10ab - github com](https://user-images.githubusercontent.com/1569463/107305431-d25d2f80-6a37-11eb-89e9-59b78ee9cf87.png)

**Comment by lukefretwell** [comment]
I'm not getting them as much so closing out for now.
