### ISSUE TITLE
Add CA logo to Accessibility site

### ISSUE THREAD

**Issue by jaube05** [CivicActions/accessibility#563]

**Comment by mgifford** [comment]
Would be great to have this up ![Red_CA Full Logo_1292x204-minimized](https://user-images.githubusercontent.com/116832/129042693-5ae1066a-8b2d-46fb-ae11-d82533d8bc16.png)

**Comment by jaube05** [comment]
<img width="1020" alt="Screen Shot 2021-08-12 at 2 39 13 PM" src="https://user-images.githubusercontent.com/62511019/129250825-87908eb8-7b15-4797-9a14-94ae17b41f0f.png">
