### ISSUE TITLE
Whitehouse Accessibility Statement Blog

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#57]
Internal Notes https://docs.google.com/document/d/197A963z54y7LC-PV3epkftmkKzToeKeOH1aQnNA83CM/edit

**Comment by lukefretwell** [comment]
Article is up!

https://www.govtech.com/opinion/How-Will-Biden-Transform-Government-Website-Accessibility.html

**Comment by lukefretwell** [comment]
https://civicactions.github.io/accessibility/posts/govtech-how-will-biden-transform-government-website-accessibility
