### ISSUE TITLE
Create accessible Google Doc template/styles

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#62]
We should create a more accessible CivicActions Google Doc template.

cc @mgifford for feedback

**Comment by mgifford** [comment]
Agreed. I proposed this - https://docs.google.com/document/d/1PlKwJl6UWZ52JJ5dgcDgxD2xRIgyOrFxI2HBhPPTyj4/edit

It also needs to be something that needs to be changed in the onboarding + with existing staff. We'd need to do an AHC on it to tell people why they need to update their default template and some of the advantages of the new model.

**Comment by lukefretwell** [comment]
@mgifford I removed my doc so we can just focus on the one you created.

**Comment by lukefretwell** [comment]
Dupe of #59
