### ISSUE TITLE
Create links to resources on appropriate terminology 

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#63]
We want to be respectful of how people want to be identified. This changes over time. 

- https://en.wikipedia.org/wiki/List_of_disability-related_terms_with_negative_connotations
- https://www.quickanddirtytips.com/education/grammar/what-to-call-people-with-disabilities
- https://www.mobility-advisor.com/disability-etiquette.html
- https://ncdj.org/style-guide/
- https://hiehelpcenter.org/2018/09/25/disability-terminology-choosing-right-words-talking-disability/
- http://nda.ie/Publications/Attitudes/Appropriate-Terms-to-Use-about-Disability/
- https://blog.ongig.com/writing-job-descriptions/a-list-of-offensive-exclusionary-words-used-in-job-descriptions/

We don't need to maintain this list, but simply find & reference it.

**Comment by lukefretwell** [comment]
@mgifford would this be part of the guide? If so, under what section?

**Comment by mgifford** [comment]
I'm not sure. It could be a short list in the guide, or we could put it into a playbook with more information around how we are incorporating automated testing into our process to see that we are catching words like this from our own documentation.
