### ISSUE TITLE
Create list of podcast, videos & newsletters

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#64]
We should highlight newsletters & podcasts where folks can learn more

## Pocasts
- https://a11yrules.com/
- https://interactiveaccessibility.com/iap-podcasts
- https://www.ruhglobal.com/podcasthuman-potential-work/
- https://www.bemyeyes.com/podcasts-show/13-letters
- https://www.bemyeyes.com/podcasts-show/the-be-my-eyes-podcast
- https://atbanter.com/

## Videos
- Heydon's Webbed Briefs - https://briefs.video/
- Erik Kroes - https://www.youtube.com/channel/UCwrpGO76k2HyUQspl-rG2eQ/videos
- Eric Eggert - https://www.youtube.com/c/EricEggert

## Twitch
- erikKroes - https://www.twitch.tv/erikKroes
- Ruh Global Impact - https://www.twitch.tv/ruh_global_impact

## Newsletters
- http://www.webaxe.org/digital-accessibility-newsletters/

**Comment by mgifford** [comment]
@lukefretwell @jerseycheese @dmundra what do you think about adding this to the resources page here: 
https://github.com/CivicActions/accessibility/blob/main/_handbook/resources.md

Or should this growing list of multi-media be it's own page?

**Comment by dmundra** [comment]
I would say the existing resources page would be fine with the headings.

**Comment by mgifford** [comment]
We can always move it later, but I've added it here https://civicactions.github.io/accessibility/handbook/resources

I'll also add it to here https://github.com/accessibility/a11y-lists-of-lists

**Comment by mgifford** [comment]
This should be marked as done. It's all on the resources page now.
