### ISSUE TITLE
Create subdomain

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#67]
@grugnog thoughts on making this repo accessibility.civicactions.com subdomain?

**Comment by lukefretwell** [comment]
Per convo @mgifford had with @grugnog, adding the two of you to this to implement.

**Comment by grugnog** [comment]
Done http://accessibility.civicactions.com/ - once Github provisions an SSL cert (~ hour) we should enable "Enforce SSL" on https://github.com/CivicActions/accessibility/settings

**Comment by lukefretwell** [comment]
@grugnog I just did enforce HTTPS, but now getting this error:

> Domain does not resolve to the GitHub Pages server. For more information, see https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/.

**Comment by grugnog** [comment]
@lukefretwell the domain is resolving, but SSL won't work until Github provisions an SSL cert

**Comment by grugnog** [comment]
```dig accessibility.civicactions.com +nostats +nocomments +nocmd
;accessibility.civicactions.com.	IN	A
accessibility.civicactions.com.	300 IN	CNAME	civicactions.github.io.
civicactions.github.io.	3599	IN	A	185.199.110.153
civicactions.github.io.	3599	IN	A	185.199.111.153
civicactions.github.io.	3599	IN	A	185.199.108.153
civicactions.github.io.	3599	IN	A	185.199.109.153```

**Comment by grugnog** [comment]
The GUI is still complaining, but I think it's just DNS caching as SSL Enforcing is enabled and working now, so closing this
