### ISSUE TITLE
Add a "Help improve this page" block on the footer

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#79]
I like how the W3C does this - https://www.w3.org/WAI/people-use-web/abilities-barriers/

Not that we want the email, but really great to have that direct link to GitHub and encouragement for folks to get involved. This is a nice way to bind open and accessibility.

**Comment by lukefretwell** [comment]
@mgifford note there's an 'Edit this page' link at the bottom of all pages. 

We should:

- [ ] Move it higher
- [ ] Change the text to 'Help improve this page'
- [ ] Fix the bug that will make the link actually work :-)

**Comment by mgifford** [comment]
I think I've fixed 2 & 3 for most pages.  With moving it higher? Think it makes sense to have it
- [ ] Floating right from the Return to top
- [ ] Under last updated
- [ ] Where it is, but just as a bigger font
- [ ] It's fine, leave it

**Comment by lukefretwell** [comment]
@mgifford I'll push my suggestion in a new update shortly.

**Comment by lukefretwell** [comment]
@mgifford this is done.
