### ISSUE TITLE
Merge Join Us & Contact

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#80]
These have basically the same information.  I'd suggest we move the email to the **[Join Us](https://civicactions.github.io/accessibility/join)** page and nix the **[Contact](https://civicactions.github.io/accessibility/contact)** page.

**Comment by lukefretwell** [comment]
@mgifford these are different contexts. One is for joining the group and getting involved and the other is simply to contact.

**Comment by mgifford** [comment]
But there is contact information in the footer as well. Just seems this is redundant.

**Comment by lukefretwell** [comment]
@mgifford I think it's good practice to have a /contact page and not just rely on footer information, as it's a big assumption people know to look there. I'm going to close this out but if you feel strongly, please open it up and make the changes you think are necessary.
