### ISSUE TITLE
Is this site for partners or the community?

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#81]
When looking at the About page I was struck by this line:
> CivicActions Accessibility is an open project and community for CivicActions team members and our **partners**.

I wondered if we should broaden it up:
> CivicActions Accessibility is an open project and community for CivicActions team members and the **community**. We want this resource to be useful to our team, our clients, our partners, but also people keen on improving accessibility on the web. 

There is lots of space, why not be more encouraging and open.

**Comment by lukefretwell** [comment]
@mgifford I will add this (with slight edits) when I push my updates.

**Comment by lukefretwell** [comment]
@mgifford updated
