### ISSUE TITLE
Latest CivicActions Accessibility News

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#82]
I like having somewhere to feature stuff we are doing on accessibility on the [News](https://civicactions.github.io/accessibility/news/) page. We just need to be getting in the habit of adding it. 

We've got this great article by Luke to talk about https://gcn.com/articles/2021/02/04/accessibility-compliance-as-code.aspx

But also these two pieces I've done:
- https://medium.com/civicactions/whitehouse-gov-makes-an-accessibility-statement-5de37580209
- https://medium.com/civicactions/4-ways-to-improve-government-accessibility-through-open-source-8e20fabc7281

Have we done anything else we should highlight?

**Comment by lukefretwell** [comment]
@mgifford added posts (left out White House for when it publishes on GT). At some point we should figure out an editorial strategy for this, but I think it's OK to experiment for the short-term. 

Also:

* Cleaned up and simplified the /news template: https://civicactions.github.io/accessibility/news/
* Enhanced the post template (ex: https://civicactions.github.io/accessibility/posts/improve-government-accessibility-through-open-source)
* Added posts to profile pages (ex: https://civicactions.github.io/accessibility/people/mike-gifford)

Closing this, but definitely think there's room for improvement.
