### ISSUE TITLE
Set up /playbook

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#83]
I've got a bunch of content I would like to publish here so that it could be used with multiple clients going ahead. Particularly in reports to clients. 

They include:
  - Common Digital Accessibility Challenges
  - Inaccessible Documentation
  - Automated Testing
  - Invest in Accessibility Training
  - Build a Community of Practice
  - Improve Authoring Tools
  - Add Accessibility Statements
  - Include People with Disabilities

Each of which could be their own page with content that is ready to be published (least as a draft).

**Comment by mgifford** [comment]
To provide more practical examples. I'll post a few:

## Follow Global Initiatives

The European Union is providing a lot of leadership for governments that prioritize accessibility. The Web Accessibility Directive forces member states to measure their accessibility barriers by:
Identifying the barriers in existing Information Communications Technology (ICT) through automated accessibility monitoring, and creating feedback loops through accessibility statements.
Commit to being transparent and accountable by regularly publishing results which allow constituents to see progress on our inclusion goals. 

They are also investing in prevention by participating in and leading initiatives that make implementing accessibility easier for everyone. They are making it easier for everyone to have more accessible sites by investing in common Content Management System (CMS) templates and improving the authoring tools.

While we have yet to uniformly implement global accessibility standards, the European Commission strategy has started working more closely with the W3C’s Web Accessibility Initiative (WAI) to implement best practices. 

The two entities co-sponsor a project to build an authoritative guide—WAI-Guide— to support international cooperation for training, advocacy, and capacity building. They are also co-sponsoring another project—WAI-Tools—to develop advanced tools for scalable web accessibility assessments. This public-facing work both contributes to the practice of open government, and ensures that the tools they develop can be maintained by a broader community.

**Comment by mgifford** [comment]
## Invest in Accessibility Training (Especially When It’s Free!)

Despite increased investment in accessibility, many government staff have not received adequate (or any) accessibility-specific training. Even as there are many resources available there is generally a lack of awareness—but when people find these resources they are often quick to take advantage. For example, when the UK’s Government Digital Services (GDS) offered a free course on content design through Future Learn, over 10 thousand people signed up. 

Some of our favorite, free accessibility courses include:
Web Accessibility by Google;
Digital Accessibility Foundations by the W3C; 
Information and Communication Technology (ICT) Accessibility by GeorgiaTech;
Assistive technologies and online learning by the Open University.

Aside from coursework, podcasts are another great way to learn about web accessibility—including A11yRules.com, Interactive Accessibility and Human Potential At Work. While these resources are often available for free, the publishers usually depend on donations to support the ongoing education work. If you choose to listen, please consider contributing to a Patreon campaign to support their wonderful work. In addition Supporting these initiatives is a cost-effective way to increase the availability of new accessibility resources. 

There are also several high-quality accessibility guides available for free. The GDS has produced accessibility guides, as has the US government’s 18F. Rather than creating a new guide from scratch, these resources are available to build upon and improve. CivicActions is looking to extend these and other resources to provide an accessibility playbook for our clients and others interested in accessibility best practices.  

Public sector employees must be encouraged to take advantage of these resources to best serve their constituents. Accessibility best practices change quickly, so it is important to invest in a sustainable accessibility training program.

**Comment by lukefretwell** [comment]
@mgifford seems like this is more of a playbook for action. What about having a /playbook that is similar to the guide but more focused on call to action/checklist, whereas the guide is more of a compilation of resources?

**Comment by mgifford** [comment]
Challenge with that is what are we calling this site. We can't call it a **handbook** (as that is going to get confusing).  The biggest alternative is to call it a **playbook**. We've thought about calling it a **practice** but that has issues too.  Could just be **better practices** (with the focus on improving over time) or **guidance**. 

I don't know.

**Comment by lukefretwell** [comment]
Two challenges to address are:

* How do I know I'm doing accessibility right?
* Where do I turn to execute this?

The former would be a playbook. The latter is the guide.

'Better practices' is fine but what would be helpful is to give direction, make it more of a CTA, actionable.

**Comment by mgifford** [comment]
Playbook formats to consider:
 - https://github.com/usds/playbook & https://playbook.cio.gov/
 - https://github.com/18F/accessibility & https://accessibility.18f.gov/
 - https://tech.gsa.gov/playbooks/
 - https://www.gov.uk/guidance/social-media-playbook
 - https://www.section508.gov/tools/playbooks/technology-accessibility-playbook-intro
 - https://section508.gov/508-training/courses/playbook/
 - https://github.com/monum/playbook & https://monum.github.io/playbook/#plays_index_anchor
 - https://github.com/GSA/participation-playbook & https://digital.gov/guides/public-participation/
 
Some here might be worth pointing to too.

**Comment by lukefretwell** [comment]
@mgifford do you have an issue (and accompanying doc) for building the MVP playbook?

Would be great to do that and document this: https://github.com/CivicActions/accessibility/issues/83#issue-803817073

**Comment by lukefretwell** [comment]
@mgifford get to work :-)

https://civicactions.github.io/accessibility/playbook
