### ISSUE TITLE
Repurpose content from Early Draft Handbook

### ISSUE THREAD

**Issue by jerseycheese** [CivicActions/accessibility#85]
Review [Early Draft Handbook](https://docs.google.com/document/d/1_zbP87VHT_XMOAyER0gNhNFSvYfcsnR13lMxOo8nEi4/edit?usp=sharing) for any info than can be retained, mark it as such, move it wherever it should be.

**Comment by jerseycheese** [comment]
TODO:
- [ ] Review Early Draft Handbook to see if anything should be ported to a11y site
- [ ] Mark doc as deprecated, w/ link to a11y site

**Comment by jerseycheese** [comment]
gDoc being used for auditing Early Draft Handbook:
https://docs.google.com/document/d/1sqhVpYAB90Tdbv4bf_j7X5dFDj_eRhTmkGOhkAVNa7g/edit?usp=sharing

**Comment by lukefretwell** [comment]
@jerseycheese @mgifford I moved things into (what I *think* are the appropriate docs and marked as deprecated)
