### ISSUE TITLE
Add LinkedIN link in footer

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#9]
https://github.com/CivicActions/accessibility/blob/main/_data/footer.yml

https://www.linkedin.com/company/civicactions/

**Comment by mgifford** [comment]
I suspect it's something like this:

```
    - text: LinkedIn
      href: https://www.linkedin.com/company/civicactions/
      external: true
      type: linkedin
```

**Comment by lukefretwell** [comment]
@brianseek how do I add a LinkedIn icon? https://designsystem.digital.gov/components/footer/

See footer: https://civicactions.github.io/accessibility/

**Comment by lukefretwell** [comment]
Done: https://civicactions.github.io/accessibility/

Thank you for the help @brianseek!
