### ISSUE TITLE
Compiling VPAT markdown to HTML

### ISSUE THREAD

**Issue by dmundra** [CivicActions/accessibility#92]
Hey @mgifford,

I noticed you updated the [VPAT md file](https://github.com/CivicActions/accessibility/blob/main/VPAT/Drupal9AccessibilityConformanceReport.md) but the [VPAT that is shown on the website](https://civicactions.github.io/accessibility/VPAT/Drupal9AccessibilityConformanceReport.html) doesn't appear to have your updates.

It seems like the [HTML version in the filesystem](https://github.com/CivicActions/accessibility/blob/main/VPAT/Drupal9AccessibilityConformanceReport.html) is the one that is rendered. Is there a different way to generate the HTML file or some special steps in Jekyll to convert it?

It has 3 minor accessibility issues that I noted in #52 (not axe) that I was looking at fixing but came up empty.

Thoughts?

**Comment by mgifford** [comment]
The report here should be dated https://civicactions.github.io/accessibility/VPAT/Drupal9AccessibilityConformanceReport.html

At best it is a snapshot of where things where. 

It shouldn't be much of a struggle to generate an html version from https://github.com/CivicActions/accessibility/blob/main/VPAT/Drupal9AccessibilityConformanceReport.md but I'm not really sure the best way to do it. 

So basically I don't know, except that there will be improvements made to Drupal9AccessibilityConformanceReport.md and probably not the others.

**Comment by dmundra** [comment]
@mgifford, I believe the VPAT HTML (and probably the MD) file were both generated from the ODT file. I tested removing the HTML file to see what Jekyll would do and this is the result: https://dmundra.github.io/accessibility/VPAT/Drupal9AccessibilityConformanceReport

It is applying the theme layout and duplicating the header. I also noticed some minor issues with the table markdown code. Also, in this format, the VPAT pages are not appearing in the sitemap because there are no menu items pointing to it (I think that is the case).

Would you like to continue using the ODT file and the version of HTML it generates or switch to markdown and the version that Jekyll generates?

**Comment by dmundra** [comment]
@mgifford I saw you renamed the file to Drupal9AccessibilityConformanceReport-December2020.html but it didn't render on the site (https://civicactions.github.io/accessibility/VPAT/Drupal9AccessibilityConformanceReport-December2020.html returns 404). I am not sure what it is doing with the files so I will table this for now and research it again later.

**Comment by mgifford** [comment]
I lost where it is liked from in the site.  It should be a 404 now, but I wanted to see if there was another way to present this, if only a symbolic link.

**Comment by dmundra** [comment]
Looks like it might just be some kind of a caching issue. It is loading now https://civicactions.github.io/accessibility/VPAT/Drupal9AccessibilityConformanceReport-December2020.html and you get this one appearing as well https://civicactions.github.io/accessibility/VPAT/Drupal9AccessibilityConformanceReport (md -> HTML)

I think the name change helped both versions appear. I am going to close this and we can revisit if it is an issue again.
